import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { motion, AnimatePresence } from "framer-motion";
import "leaflet/dist/leaflet.css";
import { CircleMarker, MapContainer, Marker, Polygon, Popup, TileLayer, useMap } from "react-leaflet";
import { divIcon, type LatLngExpression } from "leaflet";
import { ArrowUpRight, Check, ChevronDown, CircleHelp, Download, Droplets, Gauge, GitCompareArrows, History, Layers3, Leaf, MapPin, Printer, Search, ShieldCheck, Sun, Trees, Waves, Wind, X, Zap } from "lucide-react";
import { toast } from "sonner";

type CityKey = "Chennai" | "Bengaluru" | "Delhi";
type City = { city: string; state: string; lat: number; lon: number; temp: number; surface: number; utci: number; zone: string };
const cityData: Record<CityKey, City> = {
  Chennai: { city: "Chennai", state: "Tamil Nadu", lat: 13.0827, lon: 80.2707, temp: 34.8, surface: 48.2, utci: 42.6, zone: "T. Nagar / Central Chennai" },
  Bengaluru: { city: "Bengaluru", state: "Karnataka", lat: 12.9716, lon: 77.5946, temp: 28.4, surface: 38.1, utci: 32.2, zone: "Koramangala / South Bengaluru" },
  Delhi: { city: "Delhi", state: "Delhi NCR", lat: 28.6139, lon: 77.209, temp: 41.2, surface: 53.6, utci: 47.1, zone: "Lajpat Nagar / South Delhi" },
};
const cityKeys = Object.keys(cityData) as CityKey[];

function Ticker({ value, decimals = 1, prefix = "", suffix = "" }: { value: number; decimals?: number; prefix?: string; suffix?: string }) {
  const [current, setCurrent] = useState(value);
  useEffect(() => { const start = performance.now(); const from = current; let frame = 0; const run = (now: number) => { const p = Math.min(1, (now - start) / 420); const ease = 1 - Math.pow(1 - p, 3); setCurrent(from + (value - from) * ease); if (p < 1) frame = requestAnimationFrame(run); }; frame = requestAnimationFrame(run); return () => cancelAnimationFrame(frame); }, [value]);
  return <>{prefix}{current.toFixed(decimals)}{suffix}</>;
}

function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <motion.section className={`paper-card ${className}`} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }}>{children}</motion.section>; }
function Kicker({ children }: { children: ReactNode }) { return <div className="kicker"><span />{children}</div>; }

function QuenchLoader({ onDone }: { onDone: () => void }) {
  const [temp, setTemp] = useState(48.2);
  useEffect(() => { const started = performance.now(); const timer = window.setTimeout(onDone, 2500); let frame = 0; const tick = (now: number) => { const p = Math.min(1, (now - started) / 2200); setTemp(48.2 - 16.2 * (1 - Math.pow(1 - p, 2.4))); if (p < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => { window.clearTimeout(timer); cancelAnimationFrame(frame); }; }, [onDone]);
  return <motion.div className="quench" initial={{ opacity: 1 }} animate={{ opacity: 1 }} exit={{ y: "-100%" }} transition={{ duration: .7, ease: [0.77, 0, .175, 1] }}><div className="quench-wash" /><div className="quench-core"><div className="quench-brand">HEATSCAPE / THERMAL QUENCH</div><div className="quench-gauge"><div className="gauge-orbit orbit-a" /><div className="gauge-orbit orbit-b" /><Leaf size={48} className="quench-leaf" /><strong><Ticker value={temp} suffix="°C" /></strong></div><p>{temp > 32.1 ? "Critical Urban Heat" : "Thermal Equilibrium"}</p><div className="quench-line"><span style={{ width: `${((48.2 - temp) / 16.2) * 100}%` }} /></div><small>COOLING WAVE / MUNICIPAL THERMODYNAMICS</small></div></motion.div>;
}

function MapFocus({ city }: { city: City }) {
  const map = useMap();
  useEffect(() => { map.flyTo([city.lat, city.lon], 12, { duration: 1.2 }); }, [city, map]);
  return null;
}

const hotspotIcon = divIcon({ className: "heat-marker", html: '<span></span>' });

const riskOffsets = [[[-0.028,-0.035],[-0.006,-0.045],[0.012,-0.018],[0.004,0.014],[-0.02,0.01]], [[0.018,-0.018],[0.043,-0.004],[0.035,0.03],[0.004,0.023],[-0.01,0.0]], [[-0.018,0.018],[0.004,0.035],[0.025,0.018],[0.012,-0.008],[-0.012,-0.006]]];
function RiskLayer({ city }: { city: City }) { return <>{riskOffsets.map((offsets, index) => <Polygon key={index} positions={offsets.map(([lat, lon]) => [city.lat + lat, city.lon + lon] as LatLngExpression)} pathOptions={{ color: index === 1 ? "#ea580c" : "#c2410c", weight: 1.5, opacity: .65, fillColor: "#c2410c", fillOpacity: .13 }}><Popup><strong>Heat-risk ward {index + 1}</strong><br />Projected surface hotspot / {city.city}</Popup></Polygon>)}</>; }
function StreetMap({ city, onPick, showRisk }: { city: City; onPick: (key: CityKey) => void; showRisk: boolean }) {
  const center: LatLngExpression = [city.lat, city.lon];
  return <div className="street-map"><MapContainer center={center} zoom={12} scrollWheelZoom className="leaflet-map"><TileLayer attribution='&copy; OpenStreetMap &copy; CARTO' url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" /><MapFocus city={city} />{showRisk && <RiskLayer city={city} />}<CircleMarker center={center} radius={95} pathOptions={{ color: "#c2410c", weight: 1, opacity: .28, fillColor: "#c2410c", fillOpacity: .06 }} /><Marker position={center} icon={hotspotIcon}><Popup><strong>{city.city} hotspot</strong><br />Surface temperature {city.surface.toFixed(1)}°C</Popup></Marker>{cityKeys.filter((key) => key !== city.city).map((key) => <CircleMarker key={key} center={[cityData[key].lat, cityData[key].lon]} radius={6} pathOptions={{ color: "#c2410c", fillColor: "#c2410c", fillOpacity: .85 }} eventHandlers={{ click: () => onPick(key) }} />)}</MapContainer><div className="map-label"><span className="hot-dot" />{city.city.toUpperCase()} / LIVE HOTSPOT FOCUS <b>{city.lat.toFixed(4)}°N&nbsp; {city.lon.toFixed(4)}°E</b></div></div>;
}
function Toggle({ label, hint, checked, onChange, icon }: { label: string; hint: string; checked: boolean; onChange: () => void; icon: ReactNode }) { return <button className={`light-toggle ${checked ? "checked" : ""}`} onClick={onChange}><span className="toggle-icon">{icon}</span><span><b>{label}</b><small>{hint}</small></span><i><em /></i></button>; }
function Plan({ letter, title, subtitle, color, drop, roi, payback, emissions, icon, featured = false }: { letter: string; title: string; subtitle: string; color: string; drop: number; roi: number; payback: number; emissions: number; icon: ReactNode; featured?: boolean }) { return <motion.article className={`plan-light ${featured ? "featured-plan" : ""}`} style={{ "--plan": color } as React.CSSProperties} whileHover={{ y: -5 }}><div className="plan-light-top"><span>{letter}</span><b>{featured ? "RECOMMENDED MUNICIPAL TENDER" : "OPTIMIZED SCENARIO"}</b><ArrowUpRight size={15} /></div><div className="plan-light-icon">{icon}</div><h3>{title}</h3><p>{subtitle}</p><div className="plan-grid"><div><strong>−<Ticker value={drop} suffix="°C" /></strong><span>UTCI DROP</span></div><div><strong>+<Ticker value={roi} suffix="%" /></strong><span>5-YR ROI</span></div><div><strong><Ticker value={payback} suffix=" YRS" /></strong><span>PAYBACK</span></div><div><strong>−<Ticker value={emissions} decimals={0} suffix=" t" /></strong><span>NET CO2E REDUCED</span></div></div></motion.article>; }

function ComparisonModal({ calc, city, onClose }: { calc: any; city: City; onClose: () => void }) { const rows = [["UTCI DROP", `−${calc.planA.toFixed(1)}°C`, `−${calc.planB.toFixed(1)}°C`], ["5-YR ROI", `+${calc.aRoi.toFixed(1)}%`, `+${calc.bRoi.toFixed(1)}%`], ["PAYBACK", `${(3.8 - calc.lakhs * .025).toFixed(1)} YRS`, "4.5 YRS"], ["NET CO2E", `−${Math.round(270 + calc.lakhs * 13)} t`, `−${Math.round(400 + calc.lakhs * 15)} t`]]; return <motion.div className="feature-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div className="comparison-sheet" initial={{ y: 20 }} animate={{ y: 0 }}><button className="paper-close" onClick={onClose}><X size={17} /></button><Kicker>SCENARIO COMPARISON / {city.city.toUpperCase()}</Kicker><h2>Plan A vs Plan B</h2><p>Evaluate cooling intensity against long-term ecological return for the active municipal zone.</p><div className="comparison-head"><div>METRIC</div><strong className="lapis">A / MAXIMUM COOLING</strong><strong className="sage">B / ECO-FORESTRY</strong></div>{rows.map(([label, a, b]) => <div className="comparison-row" key={label}><span>{label}</span><b>{a}</b><b>{b}</b></div>)}<div className="comparison-note"><Droplets size={16} /> Plan A prioritizes immediate thermal relief; Plan B compounds canopy and emissions benefits over a longer horizon.</div></motion.div></motion.div>; }
function SavedDrawer({ scenarios, onClose, onLoad }: { scenarios: any[]; onClose: () => void; onLoad: (scenario: any) => void }) { return <motion.aside className="saved-drawer" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }}><div className="drawer-head"><div><Kicker>SAVED SCENARIOS</Kicker><h2>BoQ tender history</h2></div><button onClick={onClose}><X size={17} /></button></div>{scenarios.length === 0 ? <div className="drawer-empty"><History size={28} /><b>No saved tenders yet</b><span>Export a municipal tender to keep a quick session copy here.</span></div> : <div className="scenario-list">{scenarios.map((scenario) => <button className="scenario-item" key={scenario.id} onClick={() => onLoad(scenario)}><span><b>{scenario.city}</b><small>{scenario.zone}</small></span><strong>₹{scenario.budget.toFixed(1)}L</strong><small>{scenario.savedAt}</small></button>)}</div>}</motion.aside>; }

export default function Home() {
  const [loading, setLoading] = useState(true); const [cityKey, setCityKey] = useState<CityKey>("Chennai"); const [activeCity, setActiveCity] = useState<City>(cityData.Chennai); const [query, setQuery] = useState("Chennai"); const [budget, setBudget] = useState(2700000); const [utilities, setUtilities] = useState(false); const [transit, setTransit] = useState(true); const [tenderOpen, setTenderOpen] = useState(false); const [compareOpen, setCompareOpen] = useState(false); const [savedOpen, setSavedOpen] = useState(false); const [showRisk, setShowRisk] = useState(false); const [scenarios, setScenarios] = useState<any[]>(() => { try { return JSON.parse(localStorage.getItem("heatscape-scenarios") || "[]"); } catch { return []; } }); const city = activeCity;
  const calc = useMemo(() => { const lakhs = budget / 100000; const planA = 2.2 + lakhs * .085; const planB = 1.8 + lakhs * .06; const planC = 1.35 + lakhs * .045; return { lakhs, planA, planB, planC, roofs: Math.floor(budget * .6 / 160), trees: utilities ? Math.min(120, Math.floor(budget * .4 / 1400)) : Math.floor(budget * .4 / 1400), aRoi: 14.5 + lakhs * .15, bRoi: 10.8 + lakhs * .06, cRoi: 12.4 + lakhs * .09 }; }, [budget, utilities]);
  const chooseCity = (key: CityKey) => { setCityKey(key); setActiveCity(cityData[key]); setQuery(key); };
  const saveScenario = () => { const next = [{ id: Date.now(), city: city.city, state: city.state, zone: city.zone, lat: city.lat, lon: city.lon, temp: city.temp, surface: city.surface, utci: city.utci, budget: budget / 100000, plan: "A / Maximum Cooling", savedAt: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }, ...scenarios].slice(0, 8); setScenarios(next); localStorage.setItem("heatscape-scenarios", JSON.stringify(next)); setTenderOpen(true); };
  const loadScenario = (scenario: any) => { setQuery(scenario.city); setBudget(Math.round(scenario.budget * 100000)); if (scenario.lat && scenario.lon) setActiveCity({ city: scenario.city, state: scenario.state || "", zone: scenario.zone || scenario.city, lat: scenario.lat, lon: scenario.lon, temp: scenario.temp ?? city.temp, surface: scenario.surface ?? city.surface, utci: scenario.utci ?? city.utci }); setSavedOpen(false); toast.success("Scenario restored", { description: `${scenario.city} / ₹${scenario.budget.toFixed(1)}L` }); };
  const searchCity = async () => {
    const normalized = query.trim();
    const match = cityKeys.find((key) => key.toLowerCase() === normalized.toLowerCase());
    try {
      const geoResponse = await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(normalized)}`, { headers: { Accept: "application/json" } });
      if (!geoResponse.ok) throw new Error("Geocoder unavailable");
      const places = await geoResponse.json();
      if (!places[0]) throw new Error("City not found");
      const lat = Number(places[0].lat); const lon = Number(places[0].lon);
      const weatherResponse = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature&timezone=auto`);
      if (!weatherResponse.ok) throw new Error("Weather feed unavailable");
      const weather = await weatherResponse.json(); const current = weather.current ?? {};
      const fallback = match ? cityData[match] : cityData.Chennai;
      const resolved: City = { city: (places[0].display_name?.split(",")[0] || normalized) as string, state: places[0].display_name?.split(",")[1]?.trim() || fallback.state, lat, lon, temp: Number(current.temperature_2m ?? fallback.temp), surface: Number((Number(current.temperature_2m ?? fallback.temp) + 13.4).toFixed(1)), utci: Number(current.apparent_temperature ?? fallback.utci), zone: places[0].display_name || fallback.zone };
      setActiveCity(resolved); setQuery(resolved.city); if (match) setCityKey(match); toast.success("Live city telemetry synced", { description: `${resolved.city} / Nominatim + Open-Meteo` });
    } catch {
      if (match) { chooseCity(match); toast.info("Offline-safe fallback loaded", { description: "Live APIs were unavailable; using calibrated mock telemetry." }); } else toast.error("City lookup unavailable", { description: "Try Chennai, Bengaluru, or Delhi." });
    }
  };
  return <div className="light-app"><AnimatePresence>{loading && <QuenchLoader onDone={() => setLoading(false)} />}</AnimatePresence><header className="light-nav"><div className="light-brand"><span>HS</span><div><b>HEATSCAPE</b><small>URBAN HEAT REDUCTION PLANNER</small></div></div><nav><button className="active">Planner</button><button onClick={() => toast.info("Hotspots", { description: "Select a terracotta point on the globe." })}>Hotspots</button><button onClick={() => toast.info("Interventions", { description: "Plans recalculate with your budget." })}>Interventions</button></nav><div className="nav-tools"><button className="saved-nav" onClick={() => setSavedOpen(true)}><History size={14} /> SAVED <b>{scenarios.length}</b></button><span><i className="live-mark" /> LIVE MODEL</span><CircleHelp size={16} /><b>AR</b></div></header><main className="light-main"><div className="masthead"><div><Kicker>MUNICIPAL CONTROL CENTER / 07 SEP 2026</Kicker><h1>Cool the city.<br /><em>Precisely.</em></h1><p>Real-time thermodynamic modeling paired with deterministic capital optimization for municipal planners.</p></div><div className="masthead-note"><span>01</span><b>SELECT A CITY<br />MODEL THE INTERVENTION</b><ArrowUpRight size={16} /></div></div>
    <Card className="command-light"><div className="light-section-head"><Kicker>COMMAND CENTER</Kicker><small>INPUT / 01</small></div><div className="command-light-grid"><div><label>TARGET URBAN ZONE</label><div className="light-search"><MapPin size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && searchCity()} /><button onClick={searchCity}><Search size={16} /></button></div><div className="city-chips">{cityKeys.map((key) => <button key={key} className={key === cityKey ? "selected" : ""} onClick={() => chooseCity(key)}>{key}</button>)}</div></div><div className="city-readout"><div><MapPin size={16} /> {city.city}, {city.state} <span><Check size={11} /> VERIFIED</span></div><small>LAT <b>{city.lat.toFixed(4)}° N</b> &nbsp; LON <b>{city.lon.toFixed(4)}° E</b></small></div></div></Card>
    <div className="light-workspace"><Card className="globe-light"><div className="light-section-head"><Kicker>SPATIAL HEAT LAYER</Kicker><button className={`risk-toggle ${showRisk ? "active" : ""}`} onClick={() => setShowRisk(!showRisk)}><Layers3 size={13} /> {showRisk ? "RISK ZONES ON" : "SHOW RISK ZONES"}</button></div><StreetMap city={city} onPick={chooseCity} showRisk={showRisk} /></Card><Card className="board-light"><div className="light-section-head"><Kicker>PHYSICAL CONTROL BOARD</Kicker><small>INPUT / 02</small></div><label>DEPLOYMENT BUDGET</label><div className="budget-light">₹<Ticker value={budget / 100000} suffix="L" /></div><div className="physical-range"><input type="range" min="500000" max="5000000" step="50000" value={budget} onChange={(e) => setBudget(Number(e.target.value))} /><div style={{ width: `${((budget - 500000) / 4500000) * 100}%` }} /></div><div className="range-copy"><span>₹5.0L</span><span>₹50.0L</span></div><div className="light-switches"><Toggle label="Underground utilities" hint="Root barrier safety active" checked={utilities} onChange={() => setUtilities(!utilities)} icon={<ShieldCheck size={16} />} /><Toggle label="Heavy transit" hint="Transit-grade asphalt logic" checked={transit} onChange={() => setTransit(!transit)} icon={<Wind size={16} />} /></div><div className="solver-note"><ShieldCheck size={15} /> Physics-validated solver / ISO 7730 compliant</div></Card></div>
    <Card className="telemetry-light"><div className="light-section-head"><Kicker>TELEMETRY DASHBOARD / {city.zone}</Kicker><strong><i className="live-mark" /> LIVE WEATHER FEED</strong></div><div className="light-metrics"><div><span>AMBIENT TEMPERATURE</span><strong><Ticker value={city.temp} suffix="°C" /></strong><small>BASELINE SIGNAL</small></div><div><span>SURFACE TEMPERATURE</span><strong className="terracotta"><Ticker value={city.surface} suffix="°C" /></strong><small>THERMAL HOTSPOT</small></div><div><span>UTCI / PEDESTRIAN STRESS</span><strong className="lapis"><Ticker value={city.utci} suffix="°C" /></strong><small>{city.utci >= 45 ? "EXTREME DANGER" : city.utci >= 32 ? "VERY STRONG STRESS" : "MODERATE STRESS"}</small></div></div><div className="metric-foot"><span><Sun size={14} /> SOLAR 812 W/m²</span><span><Droplets size={14} /> HUMIDITY 63%</span><span><Waves size={14} /> CONFIDENCE 98.4%</span></div></Card>
    <div className="optimizer-title"><div><Kicker>OPTIMIZER ENGINE / LIVE RESPONSE</Kicker><h2>Capital plans that cool on contact.</h2></div><button className="compare-button" onClick={() => setCompareOpen(true)}><GitCompareArrows size={15} /> COMPARE PLAN A + B</button></div><div className="light-plans"><Plan featured letter="A" title="Maximum Cooling" subtitle="60% cool roofs / 40% urban canopy" color="#0284c7" drop={calc.planA} roi={calc.aRoi} payback={3.8 - calc.lakhs * .025} emissions={270 + calc.lakhs * 13} icon={<Droplets size={20} />} /><Plan letter="B" title="Eco-Forestry" subtitle="Miyawaki planting / permeable bioswales" color="#15803d" drop={calc.planB} roi={calc.bRoi} payback={4.5} emissions={400 + calc.lakhs * 15} icon={<Trees size={20} />} /><Plan letter="C" title="Rapid Tactical" subtitle="Shade sails / reflective albedo paint" color="#b45309" drop={calc.planC} roi={12.4 + calc.lakhs * .09} payback={2.8} emissions={200 + calc.lakhs * 8} icon={<Zap size={20} />} /></div><div className="light-action"><span><i className="live-mark" /> PROJECTED IMPACT <b>−{calc.planA.toFixed(1)}°C UTCI / {calc.trees} canopy units</b></span><button onClick={saveScenario}>EXPORT MUNICIPAL TENDER (BoQ) <ArrowUpRight size={16} /></button></div></main><footer className="light-footer"><span>HEATSCAPE / 2026</span><span>Urban heat decisions, made tangible.</span><span>DATA SOURCES: LANDSAT · ERA5 · OPEN-METEO</span></footer><AnimatePresence>{compareOpen && <ComparisonModal calc={calc} city={city} onClose={() => setCompareOpen(false)} />}{savedOpen && <SavedDrawer scenarios={scenarios} onClose={() => setSavedOpen(false)} onLoad={loadScenario} />}</AnimatePresence>
    <AnimatePresence>{tenderOpen && <TenderModal city={city} budget={budget} calc={calc} onClose={() => setTenderOpen(false)} />}</AnimatePresence></div>;
}

function TenderModal({ city, budget, calc, onClose }: { city: City; budget: number; calc: { roofs: number; trees: number; planA: number; aRoi: number }; onClose: () => void }) { return <motion.div className="paper-modal-wrap" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div className="tender-paper" initial={{ y: 20, scale: .98 }} animate={{ y: 0, scale: 1 }}><button className="paper-close" onClick={onClose}><X size={17} /></button><div className="paper-kicker">MUNICIPAL CORPORATION CAPITAL WORKS DIVISION</div><h2>Urban Heat Mitigation Tender</h2><p className="paper-sub">Schedule of Rates &amp; Bill of Quantities / {city.city}, {city.state}</p><div className="paper-meta"><span>PROJECT ZONE <b>{city.zone}</b></span><span>CAPITAL CEILING <b>₹{(budget / 100000).toFixed(1)}L</b></span><span>PLAN A UTCI TARGET <b>−{calc.planA.toFixed(1)}°C</b></span></div><table><thead><tr><th>ITEM</th><th>QUANTITY</th><th>UNIT RATE</th><th>TOTAL</th></tr></thead><tbody><tr><td>High-albedo cool roof coating</td><td>{calc.roofs.toLocaleString()} m²</td><td>₹160 / m²</td><td>₹{(calc.roofs * 160).toLocaleString()}</td></tr><tr><td>Native urban canopy</td><td>{calc.trees.toLocaleString()} saplings</td><td>₹1,400 / unit</td><td>₹{(calc.trees * 1400).toLocaleString()}</td></tr><tr><td>Misting corridor allowance</td><td>1 corridor</td><td>₹120,000 / unit</td><td>₹{Math.round(budget * .1).toLocaleString()}</td></tr></tbody></table><div className="approval"><div><Check size={15} /> Stage 1: Climate Budget Verified</div><div className="pending"><span /> Stage 2: Pending Tender Board Audit</div></div><div className="paper-actions"><button onClick={onClose}>Close</button><button className="print-btn" onClick={() => window.print()}><Printer size={15} /> Print / Save as PDF <ArrowUpRight size={14} /></button></div></motion.div></motion.div>; }
