import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowUpRight, Check, ChevronDown, CircleHelp, Download, Droplets, Gauge, Leaf, MapPin, Printer, Search, ShieldCheck, Sun, Trees, Waves, Wind, X, Zap } from "lucide-react";
import { toast } from "sonner";

type CityKey = "Chennai" | "Bengaluru" | "Delhi";
type City = { city: CityKey; state: string; lat: number; lon: number; temp: number; surface: number; utci: number; zone: string };
const cityData: Record<CityKey, City> = {
  Chennai: { city: "Chennai", state: "Tamil Nadu", lat: 13.0827, lon: 80.2707, temp: 34.8, surface: 48.2, utci: 42.6, zone: "T. Nagar / Central Chennai" },
  Bengaluru: { city: "Bengaluru", state: "Karnataka", lat: 12.9716, lon: 77.5946, temp: 28.4, surface: 38.1, utci: 32.2, zone: "Koramangala / South Bengaluru" },
  Delhi: { city: "Delhi", state: "Delhi NCR", lat: 28.6139, lon: 77.209, temp: 41.2, surface: 53.6, utci: 47.1, zone: "Lajpat Nagar / South Delhi" },
};
const cityKeys = Object.keys(cityData) as CityKey[];

function Ticker({ value, decimals = 1, prefix = "", suffix = "" }: { value: number; decimals?: number; prefix?: string; suffix?: string }) {
  const [current, setCurrent] = useState(value);
  useEffect(() => { const start = performance.now(); const from = current; let frame = 0; const run = (now: number) => { const p = Math.min(1, (now - start) / 420); const ease = 1 - Math.pow(1 - p, 3); setCurrent(from + (value - from) * ease); if (p < 1) frame = requestAnimationFrame(run); }; frame = requestAnimationFrame(run); return () => cancelAnimationFrame(frame); }, [value]);
  return <>{prefix}{current.toFixed(decimals)}{suffix}</>;
}

function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <motion.section className={`paper-card ${className}`} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }}>{children}</motion.section>; }
function Kicker({ children }: { children: ReactNode }) { return <div className="kicker"><span />{children}</div>; }

function QuenchLoader({ onDone }: { onDone: () => void }) {
  const [temp, setTemp] = useState(48.2);
  useEffect(() => { const started = performance.now(); const timer = window.setTimeout(onDone, 3000); let frame = 0; const tick = (now: number) => { const p = Math.min(1, (now - started) / 2600); setTemp(48.2 - 16.2 * (1 - Math.pow(1 - p, 2.4))); if (p < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => { window.clearTimeout(timer); cancelAnimationFrame(frame); }; }, [onDone]);
  return <motion.div className="quench" initial={{ opacity: 1 }} animate={{ opacity: 1 }} exit={{ y: "-100%" }} transition={{ duration: .7, ease: [0.77, 0, .175, 1] }}><div className="quench-wash" /><div className="quench-core"><div className="quench-brand">HEATSCAPE / THERMAL QUENCH</div><div className="quench-gauge"><div className="gauge-orbit orbit-a" /><div className="gauge-orbit orbit-b" /><Leaf size={48} className="quench-leaf" /><strong><Ticker value={temp} suffix="°C" /></strong></div><p>{temp > 32.1 ? "Critical Urban Heat" : "Thermal Equilibrium"}</p><div className="quench-line"><span style={{ width: `${((48.2 - temp) / 16.2) * 100}%` }} /></div><small>COOLING WAVE / MUNICIPAL THERMODYNAMICS</small></div></motion.div>;
}

function CanvasGlobe({ city, onPick }: { city: City; onPick: (key: CityKey) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const rotation = useRef(0); const dragging = useRef(false); const lastX = useRef(0);
  const hotspots = cityKeys.map((key) => ({ ...cityData[key], key }));
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext("2d"); if (!ctx) return; const dpr = window.devicePixelRatio || 1; const rect = canvas.getBoundingClientRect(); canvas.width = rect.width * dpr; canvas.height = rect.height * dpr; ctx.scale(dpr, dpr); const w = rect.width; const h = rect.height; const cx = w / 2; const cy = h / 2; const r = Math.min(w, h) * .38; let frame = 0;
    const project = (lat: number, lon: number) => { const latR = lat * Math.PI / 180; const lonR = (lon + rotation.current) * Math.PI / 180; const x = cx + r * Math.cos(latR) * Math.sin(lonR); const y = cy - r * Math.sin(latR); const z = Math.cos(latR) * Math.cos(lonR); return { x, y, z }; };
    const draw = () => { ctx.clearRect(0, 0, w, h); const gradient = ctx.createRadialGradient(cx - r * .32, cy - r * .38, 0, cx, cy, r * 1.15); gradient.addColorStop(0, "#fffdf6"); gradient.addColorStop(.72, "#f0eee6"); gradient.addColorStop(1, "#d8d3c8"); ctx.beginPath(); ctx.arc(cx, cy, r, 0, Math.PI * 2); ctx.fillStyle = gradient; ctx.shadowColor = "rgba(24,24,27,.12)"; ctx.shadowBlur = 24; ctx.fill(); ctx.shadowBlur = 0; ctx.save(); ctx.beginPath(); ctx.arc(cx, cy, r, 0, Math.PI * 2); ctx.clip(); ctx.strokeStyle = "rgba(113,113,122,.22)"; ctx.lineWidth = 1;
      for (let lat = -60; lat <= 60; lat += 20) { ctx.beginPath(); for (let lon = -180; lon <= 180; lon += 5) { const p = project(lat, lon); lon === -180 ? ctx.moveTo(p.x, p.y) : ctx.lineTo(p.x, p.y); } ctx.stroke(); }
      for (let lon = -160; lon <= 160; lon += 20) { ctx.beginPath(); for (let lat = -90; lat <= 90; lat += 5) { const p = project(lat, lon); lat === -90 ? ctx.moveTo(p.x, p.y) : ctx.lineTo(p.x, p.y); } ctx.stroke(); }
      ctx.fillStyle = "rgba(113,113,122,.12)"; [[20,77,34],[36,75,35],[11,79,28],[-6,106,40],[51,12,18],[-21,133,29]].forEach(([lat, lon, size]) => { const p = project(lat, lon); if (p.z > 0) { ctx.beginPath(); ctx.ellipse(p.x, p.y, size, size * .48, -.25, 0, Math.PI * 2); ctx.fill(); } }); ctx.restore();
      hotspots.forEach((point) => { const p = project(point.lat, point.lon); if (p.z <= 0) return; const selected = point.key === city.city; ctx.beginPath(); ctx.arc(p.x, p.y, selected ? 6 : 4, 0, Math.PI * 2); ctx.fillStyle = "#c2410c"; ctx.shadowColor = "rgba(194,65,12,.5)"; ctx.shadowBlur = 10; ctx.fill(); ctx.shadowBlur = 0; ctx.beginPath(); ctx.arc(p.x, p.y, selected ? 17 : 12, 0, Math.PI * 2); ctx.strokeStyle = "rgba(194,65,12,.4)"; ctx.lineWidth = 1; ctx.stroke(); if (selected) { ctx.beginPath(); ctx.arc(p.x, p.y, 27 + Math.sin(Date.now() / 400) * 3, 0, Math.PI * 2); ctx.strokeStyle = "rgba(194,65,12,.18)"; ctx.stroke(); } }); frame = requestAnimationFrame(draw); }; draw(); return () => cancelAnimationFrame(frame); }, [city]);
  useEffect(() => { const target = city.lon; const current = rotation.current; const delta = target - current; rotation.current += delta * .05; }, [city]);
  return <div className="canvas-globe"><canvas ref={canvasRef} onPointerDown={(e) => { dragging.current = true; lastX.current = e.clientX; canvasRef.current?.setPointerCapture(e.pointerId); }} onPointerMove={(e) => { if (!dragging.current) return; rotation.current += (e.clientX - lastX.current) * .35; lastX.current = e.clientX; }} onPointerUp={() => { dragging.current = false; }} onPointerLeave={() => { dragging.current = false; }} /><div className="globe-label"><span className="hot-dot" />{city.city.toUpperCase()} / LIVE HOTSPOT FOCUS <b>{city.lat.toFixed(4)}°N&nbsp; {city.lon.toFixed(4)}°E</b></div></div>;
}

function Toggle({ label, hint, checked, onChange, icon }: { label: string; hint: string; checked: boolean; onChange: () => void; icon: ReactNode }) { return <button className={`light-toggle ${checked ? "checked" : ""}`} onClick={onChange}><span className="toggle-icon">{icon}</span><span><b>{label}</b><small>{hint}</small></span><i><em /></i></button>; }
function Plan({ letter, title, subtitle, color, drop, roi, payback, emissions, icon }: { letter: string; title: string; subtitle: string; color: string; drop: number; roi: number; payback: number; emissions: number; icon: ReactNode }) { return <motion.article className="plan-light" style={{ "--plan": color } as React.CSSProperties} whileHover={{ y: -5 }}><div className="plan-light-top"><span>{letter}</span><b>OPTIMIZED SCENARIO</b><ArrowUpRight size={15} /></div><div className="plan-light-icon">{icon}</div><h3>{title}</h3><p>{subtitle}</p><div className="plan-grid"><div><strong>−<Ticker value={drop} suffix="°C" /></strong><span>UTCI DROP</span></div><div><strong>+<Ticker value={roi} suffix="%" /></strong><span>5-YR ROI</span></div><div><strong><Ticker value={payback} suffix=" YRS" /></strong><span>PAYBACK</span></div><div><strong>−<Ticker value={emissions} decimals={0} suffix=" t" /></strong><span>CO2E REDUCED</span></div></div></motion.article>; }

export default function Home() {
  const [loading, setLoading] = useState(true); const [cityKey, setCityKey] = useState<CityKey>("Chennai"); const [query, setQuery] = useState("Chennai"); const [budget, setBudget] = useState(2700000); const [utilities, setUtilities] = useState(false); const [transit, setTransit] = useState(true); const [tenderOpen, setTenderOpen] = useState(false); const city = cityData[cityKey];
  const calc = useMemo(() => { const lakhs = budget / 100000; const planA = 2.2 + lakhs * .085; const planB = 1.8 + lakhs * .06; const planC = 1.35 + lakhs * .045; return { lakhs, planA, planB, planC, roofs: Math.floor(budget * .6 / 160), trees: utilities ? Math.min(120, Math.floor(budget * .4 / 1400)) : Math.floor(budget * .4 / 1400), aRoi: 14.5 + lakhs * .15, bRoi: 10.8 + lakhs * .06, cRoi: 12.4 + lakhs * .09 }; }, [budget, utilities]);
  const chooseCity = (key: CityKey) => { setCityKey(key); setQuery(key); };
  const searchCity = () => { const match = cityKeys.find((key) => key.toLowerCase() === query.trim().toLowerCase()); match ? chooseCity(match) : toast.error("Try Chennai, Bengaluru, or Delhi"); };
  return <div className="light-app"><AnimatePresence>{loading && <QuenchLoader onDone={() => setLoading(false)} />}</AnimatePresence><header className="light-nav"><div className="light-brand"><span>HS</span><div><b>HEATSCAPE</b><small>URBAN HEAT REDUCTION PLANNER</small></div></div><nav><button className="active">Planner</button><button onClick={() => toast.info("Hotspots", { description: "Select a terracotta point on the globe." })}>Hotspots</button><button onClick={() => toast.info("Interventions", { description: "Plans recalculate with your budget." })}>Interventions</button></nav><div className="nav-tools"><span><i className="live-mark" /> LIVE MODEL</span><CircleHelp size={16} /><b>AR</b></div></header><main className="light-main"><div className="masthead"><div><Kicker>MUNICIPAL CONTROL CENTER / 07 SEP 2026</Kicker><h1>Cool the city.<br /><em>Precisely.</em></h1><p>Real-time thermodynamic modeling paired with deterministic capital optimization for municipal planners.</p></div><div className="masthead-note"><span>01</span><b>SELECT A CITY<br />MODEL THE INTERVENTION</b><ArrowUpRight size={16} /></div></div>
    <Card className="command-light"><div className="light-section-head"><Kicker>COMMAND CENTER</Kicker><small>INPUT / 01</small></div><div className="command-light-grid"><div><label>TARGET URBAN ZONE</label><div className="light-search"><MapPin size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && searchCity()} /><button onClick={searchCity}><Search size={16} /></button></div><div className="city-chips">{cityKeys.map((key) => <button key={key} className={key === cityKey ? "selected" : ""} onClick={() => chooseCity(key)}>{key}</button>)}</div></div><div className="city-readout"><div><MapPin size={16} /> {city.city}, {city.state} <span><Check size={11} /> VERIFIED</span></div><small>LAT <b>{city.lat.toFixed(4)}° N</b> &nbsp; LON <b>{city.lon.toFixed(4)}° E</b></small></div></div></Card>
    <div className="light-workspace"><Card className="globe-light"><div className="light-section-head"><Kicker>SPATIAL HEAT LAYER</Kicker><strong>LIVE / GIS</strong></div><CanvasGlobe city={city} onPick={chooseCity} /></Card><Card className="board-light"><div className="light-section-head"><Kicker>PHYSICAL CONTROL BOARD</Kicker><small>INPUT / 02</small></div><label>DEPLOYMENT BUDGET</label><div className="budget-light">₹<Ticker value={budget / 100000} suffix="L" /></div><div className="physical-range"><input type="range" min="500000" max="5000000" step="50000" value={budget} onChange={(e) => setBudget(Number(e.target.value))} /><div style={{ width: `${((budget - 500000) / 4500000) * 100}%` }} /></div><div className="range-copy"><span>₹5.0L</span><span>₹50.0L</span></div><div className="light-switches"><Toggle label="Underground utilities" hint="Root barrier safety active" checked={utilities} onChange={() => setUtilities(!utilities)} icon={<ShieldCheck size={16} />} /><Toggle label="Heavy transit" hint="Transit-grade asphalt logic" checked={transit} onChange={() => setTransit(!transit)} icon={<Wind size={16} />} /></div><div className="solver-note"><ShieldCheck size={15} /> Physics-validated solver / ISO 7730 compliant</div></Card></div>
    <Card className="telemetry-light"><div className="light-section-head"><Kicker>TELEMETRY DASHBOARD / {city.zone}</Kicker><strong><i className="live-mark" /> LIVE WEATHER FEED</strong></div><div className="light-metrics"><div><span>AMBIENT TEMPERATURE</span><strong><Ticker value={city.temp} suffix="°C" /></strong><small>BASELINE SIGNAL</small></div><div><span>SURFACE TEMPERATURE</span><strong className="terracotta"><Ticker value={city.surface} suffix="°C" /></strong><small>THERMAL HOTSPOT</small></div><div><span>UTCI / PEDESTRIAN STRESS</span><strong className="lapis"><Ticker value={city.utci} suffix="°C" /></strong><small>{city.utci >= 45 ? "EXTREME DANGER" : city.utci >= 32 ? "VERY STRONG STRESS" : "MODERATE STRESS"}</small></div></div><div className="metric-foot"><span><Sun size={14} /> SOLAR 812 W/m²</span><span><Droplets size={14} /> HUMIDITY 63%</span><span><Waves size={14} /> CONFIDENCE 98.4%</span></div></Card>
    <div className="optimizer-title"><div><Kicker>OPTIMIZER ENGINE / LIVE RESPONSE</Kicker><h2>Capital plans that cool on contact.</h2></div><span>Budget sensitivity active</span></div><div className="light-plans"><Plan letter="A" title="Maximum Cooling" subtitle="60% cool roofs / 40% urban canopy" color="#0284c7" drop={calc.planA} roi={calc.aRoi} payback={3.8 - calc.lakhs * .025} emissions={270 + calc.lakhs * 13} icon={<Droplets size={20} />} /><Plan letter="B" title="Eco-Forestry" subtitle="Miyawaki planting / permeable bioswales" color="#15803d" drop={calc.planB} roi={calc.bRoi} payback={4.5} emissions={400 + calc.lakhs * 15} icon={<Trees size={20} />} /><Plan letter="C" title="Rapid Tactical" subtitle="Shade sails / reflective albedo paint" color="#b45309" drop={calc.planC} roi={12.4 + calc.lakhs * .09} payback={2.8} emissions={200 + calc.lakhs * 8} icon={<Zap size={20} />} /></div><div className="light-action"><span><i className="live-mark" /> PROJECTED IMPACT <b>−{calc.planA.toFixed(1)}°C UTCI / {calc.trees} canopy units</b></span><button onClick={() => setTenderOpen(true)}>EXPORT MUNICIPAL TENDER (BoQ) <ArrowUpRight size={16} /></button></div></main><footer className="light-footer"><span>HEATSCAPE / 2026</span><span>Urban heat decisions, made tangible.</span><span>DATA SOURCES: LANDSAT · ERA5 · OPEN-METEO</span></footer>
    <AnimatePresence>{tenderOpen && <TenderModal city={city} budget={budget} calc={calc} onClose={() => setTenderOpen(false)} />}</AnimatePresence></div>;
}

function TenderModal({ city, budget, calc, onClose }: { city: City; budget: number; calc: { roofs: number; trees: number; planA: number; aRoi: number }; onClose: () => void }) { return <motion.div className="paper-modal-wrap" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div className="tender-paper" initial={{ y: 20, scale: .98 }} animate={{ y: 0, scale: 1 }}><button className="paper-close" onClick={onClose}><X size={17} /></button><div className="paper-kicker">MUNICIPAL CORPORATION CAPITAL WORKS DIVISION</div><h2>Urban Heat Mitigation Tender</h2><p className="paper-sub">Schedule of Rates &amp; Bill of Quantities / {city.city}, {city.state}</p><div className="paper-meta"><span>PROJECT ZONE <b>{city.zone}</b></span><span>CAPITAL CEILING <b>₹{(budget / 100000).toFixed(1)}L</b></span><span>PLAN A UTCI TARGET <b>−{calc.planA.toFixed(1)}°C</b></span></div><table><thead><tr><th>ITEM</th><th>QUANTITY</th><th>UNIT RATE</th><th>TOTAL</th></tr></thead><tbody><tr><td>High-albedo cool roof coating</td><td>{calc.roofs.toLocaleString()} m²</td><td>₹160 / m²</td><td>₹{(calc.roofs * 160).toLocaleString()}</td></tr><tr><td>Native urban canopy</td><td>{calc.trees.toLocaleString()} saplings</td><td>₹1,400 / unit</td><td>₹{(calc.trees * 1400).toLocaleString()}</td></tr><tr><td>Misting corridor allowance</td><td>1 corridor</td><td>₹120,000 / unit</td><td>₹{Math.round(budget * .1).toLocaleString()}</td></tr></tbody></table><div className="approval"><div><Check size={15} /> Stage 1: Climate Budget Verified</div><div className="pending"><span /> Stage 2: Pending Tender Board Audit</div></div><div className="paper-actions"><button onClick={onClose}>Close</button><button className="print-btn" onClick={() => window.print()}><Printer size={15} /> Print / Save as PDF <ArrowUpRight size={14} /></button></div></motion.div></motion.div>; }
